CREATE TABLE IF NOT EXISTS userinfo (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT,
  document TEXT,
  document_type TEXT,
  email TEXT,
  phone TEXT,
  nationality TEXT,
  cep TEXT,
  city TEXT,
  state TEXT,
  neighborhood TEXT,
  street TEXT,
  location TEXT,
  flags JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  house_number TEXT,
  mothers_name TEXT,
  birthday TEXT,
  active TEXT,
  uuid UUID
);