CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY,
  name TEXT,
  role TEXT,
  is_verified BOOLEAN,
  can_transact BOOLEAN,
  status TEXT,
  fee_level_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  flags JSONB,
  expo_id TEXT,
  kyc_approved BOOLEAN,
  kyc_risk TEXT,
  banking_enable BOOLEAN,
  disinterest BOOLEAN,
  register_txid TEXT,
  called_attempts_guenno INTEGER,
  stage_kyc INTEGER,
  comment_kyc TEXT,
  provider_kyc TEXT,
  attempts_kyc INTEGER,
  password TEXT,
  ip_create TEXT,
  error JSONB,
  restrict BOOLEAN,
  override_instant_pay BOOLEAN,
  uuid UUID,
  last_login TEXT,
  last_ip_login TEXT,
  retry_kyc INTEGER,
  regenerate_kyc BOOLEAN,
  master_instant_pay BOOLEAN
);