CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS actions_type (
  id SERIAL PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  description_action VARCHAR(255) NOT NULL
);